export interface WledEffectCatalogEntry {
  id: number;
  label: string;
  metadata: string;
}

export const WLED_EFFECT_CATALOG: WledEffectCatalogEntry[] = [
  { id: 0, label: "Solid", metadata: "Solid" },
  { id: 1, label: "Blink", metadata: "Blink@!,Duty cycle;!,!;!;01" },
  { id: 2, label: "Breathe", metadata: "Breathe@!;!,!;!;01" },
  { id: 3, label: "Wipe", metadata: "Wipe@!,!;!,!;!" },
  { id: 4, label: "Wipe Random", metadata: "Wipe Random@!;;!" },
  { id: 5, label: "Random Colors", metadata: "Random Colors@!,Fade time;;!;01" },
  { id: 6, label: "Sweep", metadata: "Sweep@!,!;!,!;!" },
  { id: 7, label: "Dynamic", metadata: "Dynamic@!,!,,,,Smooth;;!" },
  { id: 8, label: "Colorloop", metadata: "Colorloop@!,Saturation;;!;01" },
  { id: 9, label: "Rainbow", metadata: "Rainbow@!,Size;;!" },
  { id: 10, label: "Scan", metadata: "Scan@!,# of dots,,,,,Overlay;!,!,!;!" },
  { id: 11, label: "Scan Dual", metadata: "Scan Dual@!,# of dots,,,,,Overlay;!,!,!;!" },
  { id: 12, label: "Fade", metadata: "Fade@!;!,!;!;01" },
  { id: 13, label: "Theater", metadata: "Theater@!,Gap size;!,!;!" },
  { id: 14, label: "Theater Rainbow", metadata: "Theater Rainbow@!,Gap size;,!;!" },
  { id: 15, label: "Running", metadata: "Running@!,Wave width;!,!;!" },
  { id: 16, label: "Saw", metadata: "Saw@!,Width;!,!;!" },
  { id: 17, label: "Twinkle", metadata: "Twinkle@!,!;!,!;!;;m12=0" },
  { id: 18, label: "Dissolve", metadata: "Dissolve@Repeat speed,Dissolve speed,,,,Random,Complete;!,!;!" },
  { id: 19, label: "Dissolve Rnd", metadata: "Dissolve Rnd@Repeat speed,Dissolve speed;,!;!" },
  { id: 20, label: "Sparkle", metadata: "Sparkle@!,,,,,,Overlay;!,!;!;;m12=0" },
  { id: 21, label: "Sparkle Dark", metadata: "Sparkle Dark@!,!,,,,,Overlay;Bg,Fx;!;;m12=0" },
  { id: 22, label: "Sparkle+", metadata: "Sparkle+@!,!,,,,,Overlay;Bg,Fx;!;;m12=0" },
  { id: 23, label: "Strobe", metadata: "Strobe@!;!,!;!;01" },
  { id: 24, label: "Strobe Rainbow", metadata: "Strobe Rainbow@!;,!;!;01" },
  { id: 25, label: "Strobe Mega", metadata: "Strobe Mega@!,!;!,!;!;01" },
  { id: 26, label: "Blink Rainbow", metadata: "Blink Rainbow@Frequency,Blink duration;!,!;!;01" },
  { id: 27, label: "Android", metadata: "Android@!,Width;!,!;!;;m12=1" },
  { id: 28, label: "Chase", metadata: "Chase@!,Width;!,!,!;!" },
  { id: 29, label: "Chase Random", metadata: "Chase Random@!,Width;!,,!;!" },
  { id: 30, label: "Chase Rainbow", metadata: "Chase Rainbow@!,Width;!,!;!" },
  { id: 31, label: "Chase Flash", metadata: "Chase Flash@!;Bg,Fx;!" },
  { id: 32, label: "Chase Flash Rnd", metadata: "Chase Flash Rnd@!;!,!;!" },
  { id: 33, label: "Rainbow Runner", metadata: "Rainbow Runner@!,Size;Bg;!" },
  { id: 34, label: "Colorful", metadata: "Colorful@!,Saturation;1,2,3;!" },
  { id: 35, label: "Traffic Light", metadata: "Traffic Light@!,US style;,!;!" },
  { id: 36, label: "Sweep Random", metadata: "Sweep Random@!;;!" },
  { id: 37, label: "Chase 2", metadata: "Chase 2@!,Width;!,!;!" },
  { id: 38, label: "Aurora", metadata: "Aurora@!,!;1,2,3;!;;sx=24,pal=50" },
  { id: 39, label: "Stream", metadata: "Stream@!,Zone size;;!" },
  { id: 40, label: "Scanner", metadata: "Scanner@!,Trail,Delay,,,Dual,Bi-delay;!,!,!;!;;m12=0,c1=0" },
  { id: 41, label: "Lighthouse", metadata: "Lighthouse@!,Fade rate;!,!;!" },
  { id: 42, label: "Fireworks", metadata: "Fireworks@,Frequency;!,!;!;12;ix=192,pal=11" },
  { id: 43, label: "Rain", metadata: "Rain@!,Spawning rate;!,!;!;12;ix=128,pal=0" },
  { id: 44, label: "Tetrix", metadata: "Tetrix@!,Width,,,,One color;!,!;!;;sx=0,ix=0,pal=11,m12=1" },
  { id: 45, label: "Fire Flicker", metadata: "Fire Flicker@!,!;!;!;01" },
  { id: 46, label: "Gradient", metadata: "Gradient@!,Spread;!,!;!;;ix=16" },
  { id: 47, label: "Loading", metadata: "Loading@!,Fade;!,!;!;;ix=16" },
  { id: 48, label: "Rolling Balls", metadata: "Rolling Balls@!,# of balls,,,,Collide,Overlay,Trails;!,!,!;!;1;m12=1" },
  { id: 49, label: "Fairy", metadata: "Fairy@!,# of flashers;!,!;!" },
  { id: 50, label: "Two Dots", metadata: "Two Dots@!,Dot size,,,,,Overlay;1,2,Bg;!" },
  { id: 51, label: "Fairytwinkle", metadata: "Fairytwinkle@!,!;!,!;!;;m12=0" },
  { id: 52, label: "Running Dual", metadata: "Running Dual@!,Wave width;L,!,R;!" },
  { id: 53, label: "Image", metadata: "Image@!,Blur,;;;12;sx=128,ix=0" },
  { id: 54, label: "Chase 3", metadata: "Chase 3@!,Size;1,2,3;!" },
  { id: 55, label: "Tri Wipe", metadata: "Tri Wipe@!;1,2,3;!" },
  { id: 56, label: "Tri Fade", metadata: "Tri Fade@!;1,2,3;!" },
  { id: 57, label: "Lightning", metadata: "Lightning@!,!,,,,,Overlay;!,!;!" },
  { id: 58, label: "ICU", metadata: "ICU@!,!,,,,,Overlay;!,!;!" },
  { id: 59, label: "Multi Comet", metadata: "Multi Comet@!,Fade;!,!;!;1" },
  { id: 60, label: "Scanner Dual", metadata: "Scanner Dual@!,Trail,Delay,,,Dual,Bi-delay;!,!,!;!;;m12=0,c1=0" },
  { id: 61, label: "Stream 2", metadata: "Stream 2@!;;" },
  { id: 62, label: "Oscillate", metadata: "Oscillate" },
  { id: 63, label: "Pride 2015", metadata: "Pride 2015@!;;" },
  { id: 64, label: "Juggle", metadata: "Juggle@!,Trail;;!;;sx=64,ix=128" },
  { id: 65, label: "Palette", metadata: "Palette@Shift,Size,Rotation,,,Animate Shift,Animate Rotation,Anamorphic;;!;12;ix=112,c1=0,o1=1,o2=0,o3=1" },
  { id: 66, label: "Fire 2012", metadata: "Fire 2012@Cooling,Spark rate,,2D Blur,Boost;;!;1;pal=35,sx=64,ix=160,m12=1,c2=128" },
  { id: 67, label: "Colorwaves", metadata: "Colorwaves@!,Hue;!;!;;pal=26" },
  { id: 68, label: "Bpm", metadata: "Bpm@!;!;!;;sx=64" },
  { id: 69, label: "Fill Noise", metadata: "Fill Noise@!;!;!" },
  { id: 70, label: "Noise 1", metadata: "Noise 1@!;!;!;;pal=20" },
  { id: 71, label: "Noise 2", metadata: "Noise 2@!;!;!;;pal=43" },
  { id: 72, label: "Noise 3", metadata: "Noise 3@!;!;!;;pal=35" },
  { id: 73, label: "Noise 4", metadata: "Noise 4@!;!;!;;pal=26" },
  { id: 74, label: "Colortwinkles", metadata: "Colortwinkles@Fade speed,Spawn speed;;!;;m12=0" },
  { id: 75, label: "Lake", metadata: "Lake@!;Fx;!" },
  { id: 76, label: "Meteor", metadata: "Meteor@!,Trail,,,,Gradient,,Smooth;;!;1" },
  { id: 77, label: "Copy Segment", metadata: "Copy Segment@,Color shift,Lighten,Brighten,ID,Axis(2D),FullStack(last frame);;;12;ix=0,c1=0,c2=0,c3=0" },
  { id: 78, label: "Railway", metadata: "Railway@!,Smoothness;1,2;!;;pal=3" },
  { id: 79, label: "Ripple", metadata: "Ripple@!,Wave #,Blur,,,,Overlay;,!;!;12;c1=0" },
  { id: 80, label: "Twinklefox", metadata: "Twinklefox@!,Twinkle rate,,,,Cool;!,!;!" },
  { id: 81, label: "Twinklecat", metadata: "Twinklecat@!,Twinkle rate,,,,Cool,Reverse;!,!;!" },
  { id: 82, label: "Halloween Eyes", metadata: "Halloween Eyes@Eye off time,Eye on time,,,,,Overlay;!,!;!;12" },
  { id: 83, label: "Solid Pattern", metadata: "Solid Pattern@Fg size,Bg size;Fg,!;!;;pal=0" },
  { id: 84, label: "Solid Pattern Tri", metadata: "Solid Pattern Tri@,Size;1,2,3;;;pal=0" },
  { id: 85, label: "Spots", metadata: "Spots@Spread,Width,,,,,Overlay;!,!;!" },
  { id: 86, label: "Spots Fade", metadata: "Spots Fade@Spread,Width,,,,,Overlay;!,!;!" },
  { id: 87, label: "Glitter", metadata: "Glitter@!,!,,,,,Overlay;,,Glitter color;!;;pal=11,m12=0" },
  { id: 88, label: "Candle", metadata: "Candle@!,!;!,!;!;01;sx=96,ix=224,pal=0" },
  { id: 89, label: "Fireworks Starburst", metadata: "Fireworks Starburst@Chance,Fragments,,,,,Overlay;,!;!;;pal=11,m12=0" },
  { id: 90, label: "Fireworks 1D", metadata: "Fireworks 1D@Gravity,Firing side;!,!;!;12;pal=11,ix=128" },
  { id: 91, label: "Bouncing Balls", metadata: "Bouncing Balls@Gravity,# of balls,,,,,Overlay;!,!,!;!;1;m12=1" },
  { id: 92, label: "Sinelon", metadata: "Sinelon@!,Trail;!,!,!;!" },
  { id: 93, label: "Sinelon Dual", metadata: "Sinelon Dual@!,Trail;!,!,!;!" },
  { id: 94, label: "Sinelon Rainbow", metadata: "Sinelon Rainbow@!,Trail;,,!;!" },
  { id: 95, label: "Popcorn", metadata: "Popcorn@!,!,,,,,Overlay;!,!,!;!;;m12=1" },
  { id: 96, label: "Drip", metadata: "Drip@Gravity,# of drips,,,,,Overlay;!,!;!;;m12=1" },
  { id: 97, label: "Plasma", metadata: "Plasma@Phase,!;!;!" },
  { id: 98, label: "Percent", metadata: "Percent@!,% of fill,,,,One color;!,!;!" },
  { id: 99, label: "Ripple Rainbow", metadata: "Ripple Rainbow@!,Wave #;;!;12" },
  { id: 100, label: "Heartbeat", metadata: "Heartbeat@!,!;!,!;!;01;m12=1" },
  { id: 101, label: "Pacifica", metadata: "Pacifica@!,Angle;;!;;pal=51" },
  { id: 102, label: "Candle Multi", metadata: "Candle Multi@!,!;!,!;!;;sx=96,ix=224,pal=0" },
  { id: 103, label: "Solid Glitter", metadata: "Solid Glitter@,!;Bg,,Glitter color;;;m12=0" },
  { id: 104, label: "Sunrise", metadata: "Sunrise@Time [min],Width;;!;;pal=35,sx=60" },
  { id: 105, label: "Phased", metadata: "Phased@!,!;!,!;!" },
  { id: 106, label: "Twinkleup", metadata: "Twinkleup@!,Intensity;!,!;!;;m12=0" },
  { id: 107, label: "Noise Pal", metadata: "Noise Pal@!,Scale;;!" },
  { id: 108, label: "Sine", metadata: "Sine@!,Scale;;!" },
  { id: 109, label: "Phased Noise", metadata: "Phased Noise@!,!;!,!;!" },
  { id: 110, label: "Flow", metadata: "Flow@!,Zones;;!;;m12=1" },
  { id: 111, label: "Chunchun", metadata: "Chunchun@!,Gap size;!,!;!" },
  { id: 112, label: "Dancing Shadows", metadata: "Dancing Shadows@!,# of shadows;!;!" },
  { id: 113, label: "Washing Machine", metadata: "Washing Machine@!,!;;!" },
  { id: 114, label: "Rotozoomer", metadata: "Rotozoomer@!,Scale,,,,Alt;;!;2;pal=54" },
  { id: 115, label: "Blends", metadata: "Blends@Shift speed,Blend speed;;!" },
  { id: 116, label: "TV Simulator", metadata: "TV Simulator@!,!;;!;01" },
  { id: 117, label: "Dynamic Smooth", metadata: "Dynamic Smooth@!,!;;!" },
  { id: 118, label: "Spaceships", metadata: "Spaceships@!,Blur,,,,Smear;;!;2" },
  { id: 119, label: "Crazy Bees", metadata: "Crazy Bees@!,Blur,,,,Smear;;!;2;pal=11,ix=0" },
  { id: 120, label: "Ghost Rider", metadata: "Ghost Rider@Fade rate,Blur;;!;2" },
  { id: 121, label: "Blobs", metadata: "Blobs@!,# blobs,Blur,Trail;!;!;2;c1=8" },
  { id: 122, label: "Scrolling Text", metadata: "Scrolling Text@!,Y Offset,Trail,Font size,Rotate,Gradient,,Reverse;!,!,Gradient;!;2;ix=128,c1=0,rev=0,mi=0,rY=0,mY=0" },
  { id: 123, label: "Drift Rose", metadata: "Drift Rose@Fade,Blur,,,,Smear;;!;2;pal=11" },
  { id: 124, label: "Distortion Waves", metadata: "Distortion Waves@!,Scale,,,,Fill,Zoom,Alt;;!;2;pal=0" },
  { id: 125, label: "Soap", metadata: "Soap@!,Smoothness,Density;;!;2;pal=11" },
  { id: 126, label: "Octopus", metadata: "Octopus@!,,Offset X,Offset Y,Legs,fasttan;;!;2;" },
  { id: 127, label: "Waving Cell", metadata: "Waving Cell@!,Blur,Amplitude 1,Amplitude 2,Amplitude 3,,Flow;;!;2;ix=0" },
  { id: 128, label: "Pixels", metadata: "Pixels@Fade rate,# of pixels;!,!;!;1v;m12=0,si=0" },
  { id: 129, label: "Pixelwave", metadata: "Pixelwave@!,Sensitivity;!,!;!;1v;ix=64,m12=2,si=0" },
  { id: 130, label: "Juggles", metadata: "Juggles@!,# of balls;!,!;!;01v;m12=0,si=0" },
  { id: 131, label: "Matripix", metadata: "Matripix@!,Brightness;!,!;!;1v;ix=64,m12=2,si=1" },
  { id: 132, label: "Gravimeter", metadata: "Gravimeter@Rate of fall,Sensitivity;!,!;!;1v;ix=128,m12=2,si=0" },
  { id: 133, label: "Plasmoid", metadata: "Plasmoid@Phase,# of pixels;!,!;!;01v;sx=128,ix=128,m12=0,si=0" },
  { id: 134, label: "Puddles", metadata: "Puddles@Fade rate,Puddle size;!,!;!;1v;m12=0,si=0" },
  { id: 135, label: "Midnoise", metadata: "Midnoise@Fade rate,Max. length;!,!;!;1v;ix=128,m12=1,si=0" },
  { id: 136, label: "Noisemeter", metadata: "Noisemeter@Fade rate,Width;!,!;!;1v;ix=128,m12=2,si=0" },
  { id: 137, label: "Freqwave", metadata: "Freqwave@Speed,Sound effect,Low bin,High bin,Pre-amp;;;01f;m12=2,si=0" },
  { id: 138, label: "Freqmatrix", metadata: "Freqmatrix@Speed,Sound effect,Low bin,High bin,Sensitivity;;;01f;m12=3,si=0" },
  { id: 139, label: "GEQ", metadata: "GEQ@Fade speed,Ripple decay,# of bands,,Bin,Color bars;!,,Peaks;!;2f;c1=255,c2=64,pal=11,si=0,c3=0" },
  { id: 140, label: "Waterfall", metadata: "Waterfall@!,Adjust color,Select bin,Volume (min);!,!;!;01f;c2=0,m12=2,si=0" },
  { id: 141, label: "Freqpixels", metadata: "Freqpixels@Fade rate,Starting color and # of pixels;!,!,;!;1f;m12=0,si=0" },
  { id: 143, label: "Noisefire", metadata: "Noisefire@!,!;;;01v;m12=2,si=0" },
  { id: 144, label: "Puddlepeak", metadata: "Puddlepeak@Fade rate,Puddle size,Select bin,Volume (min);!,!;!;1v;c2=0,m12=0,si=0" },
  { id: 145, label: "Noisemove", metadata: "Noisemove@Move speed,Fade rate;!,!;!;01f;m12=0,si=0" },
  { id: 146, label: "Noise2D", metadata: "Noise2D@!,Scale;;!;2" },
  { id: 147, label: "Perlin Move", metadata: "Perlin Move@!,# of pixels,Fade rate;!,!;!" },
  { id: 148, label: "Ripple Peak", metadata: "Ripple Peak@Fade rate,Max # of ripples,Select bin,Volume (min);!,!;!;1v;c2=0,m12=0,si=0" },
  { id: 149, label: "Firenoise", metadata: "Firenoise@X scale,Y scale,,,,Palette;;!;2;pal=66" },
  { id: 150, label: "Squared Swirl", metadata: "Squared Swirl@,Fade,,,Blur;;!;2" },
  { id: 151, label: "PacMan", metadata: "PacMan@Speed,# of PowerDots,Blink distance,Blur,# of Ghosts,Dots,Smear,Compact;;!;1;m12=0,sx=192,ix=64,c1=64,c2=0,c3=12,o1=1,o2=0" },
  { id: 152, label: "DNA", metadata: "DNA@Scroll speed,Blur,,,,Smear;;!;2;ix=0" },
  { id: 153, label: "Matrix", metadata: "Matrix@!,Spawning rate,Trail,,,Custom color;Spawn,Trail;;2" },
  { id: 154, label: "Metaballs", metadata: "Metaballs@!;;!;2" },
  { id: 155, label: "Freqmap", metadata: "Freqmap@Fade rate,Starting color;!,!;!;1f;m12=0,si=0" },
  { id: 156, label: "Gravcenter", metadata: "Gravcenter@Rate of fall,Sensitivity;!,!;!;1v;ix=128,m12=2,si=0" },
  { id: 157, label: "Gravcentric", metadata: "Gravcentric@Rate of fall,Sensitivity;!,!;!;1v;ix=128,m12=3,si=0" },
  { id: 158, label: "Gravfreq", metadata: "Gravfreq@Rate of fall,Sensitivity;!,!;!;1f;ix=128,m12=0,si=0" },
  { id: 159, label: "DJ Light", metadata: "DJ Light@Speed;;;01f;m12=2,si=0" },
  { id: 160, label: "Funky Plank", metadata: "Funky Plank@Scroll speed,,# of bands;;;2f;si=0" },
  { id: 161, label: "Shimmer", metadata: "Shimmer@Speed,Interval,Size,Granular,Flow,Zebra,Reverse,Sporadic;Fx,Bg,Cx;!;1;pal=15,sx=220,ix=10,c2=0,c3=0" },
  { id: 162, label: "Pulser", metadata: "Pulser@!,Blur;;!;2" },
  { id: 163, label: "Blurz", metadata: "Blurz@Fade rate,Blur;!,Color mix;!;1f;m12=0,si=0" },
  { id: 164, label: "Drift", metadata: "Drift@Rotation speed,Blur,,,,Twin,Smear;;!;2;ix=0" },
  { id: 165, label: "Waverly", metadata: "Waverly@Amplification,Sensitivity,,,,,Blur;;!;2v;ix=64,si=0" },
  { id: 166, label: "Sun Radiation", metadata: "Sun Radiation@Variance,Brightness;;;2" },
  { id: 167, label: "Colored Bursts", metadata: "Colored Bursts@Speed,# of lines,,,Blur,Gradient,Smear,Dots;;!;2;c3=16" },
  { id: 168, label: "Julia", metadata: "Julia@,Max iterations per pixel,X center,Y center,Area size, Blur;!;!;2;ix=24,c1=128,c2=128,c3=16" },
  { id: 172, label: "Game Of Life", metadata: "Game Of Life@!,,Blur,,,,,Mutation;!,!;!;2;pal=11,sx=128" },
  { id: 173, label: "Tartan", metadata: "Tartan@X scale,Y scale,,,Sharpness;;!;2" },
  { id: 174, label: "Polar Lights", metadata: "Polar Lights@!,Scale,,,,Flip Palette;;!;2;pal=71" },
  { id: 175, label: "Swirl", metadata: "Swirl@!,Sensitivity,Blur;,Bg Swirl;!;2v;ix=64,si=0" },
  { id: 176, label: "Lissajous", metadata: "Lissajous@X frequency,Fade rate,Blur,,Speed,Smear;!;!;2;c1=0" },
  { id: 177, label: "Frizzles", metadata: "Frizzles@X frequency,Y frequency,Blur,,,Smear;;!;2" },
  { id: 178, label: "Plasma Ball", metadata: "Plasma Ball@Speed,,Fade,Blur;;!;2" },
  { id: 179, label: "Flow Stripe", metadata: "Flow Stripe@Hue speed,Effect speed;;!;pal=11" },
  { id: 180, label: "Hiphotic", metadata: "Hiphotic@X scale,Y scale,,,Speed;!;!;2" },
  { id: 181, label: "Sindots", metadata: "Sindots@!,Dot distance,Fade rate,Blur,,Smear;;!;2;" },
  { id: 182, label: "DNA Spiral", metadata: "DNA Spiral@Scroll speed,Y frequency,Blur,,,Smear;;!;2;c1=0" },
  { id: 183, label: "Black Hole", metadata: "Black Hole@Fade rate,Outer Y freq.,Outer X freq.,Inner X freq.,Inner Y freq.,Solid,,Blur;!;!;2;pal=11" },
  { id: 184, label: "Wavesins", metadata: "Wavesins@!,Brightness variation,Starting color,Range of colors,Color variation;!;!" },
  { id: 185, label: "Rocktaves", metadata: "Rocktaves@;!,!;!;01f;m12=1,si=0" },
  { id: 186, label: "Akemi", metadata: "Akemi@Color speed,Dance;Head palette,Arms & Legs,Eyes & Mouth;Face palette;2f;si=0" },
  { id: 187, label: "PS Volcano", metadata: "PS Volcano@Speed,Intensity,Move,Bounce,Spread,AgeColor,Walls,Collide;;!;2;pal=35,sx=100,ix=190,c1=0,c2=160,c3=6,o1=1" },
  { id: 188, label: "PS Fire", metadata: "PS Fire@Speed,Intensity,Flame Height,Wind,Spread,Smooth,Cylinder,Turbulence;;!;2;pal=35,sx=110,c1=110,c2=50,c3=31,o1=1" },
  { id: 189, label: "PS Fireworks", metadata: "PS Fireworks@Launches,Explosion Size,Fuse,Blur,Gravity,Cylinder,Ground,Fast;;!;2;pal=11,ix=50,c1=40,c2=0,c3=12" },
  { id: 190, label: "PS Vortex", metadata: "PS Vortex@Rotation Speed,Particle Speed,Arms,Flip,Nozzle,Smear,Direction,Random Flip;;!;2;pal=27,c1=200,c2=0,c3=0" },
  { id: 191, label: "PS Fuzzy Noise", metadata: "PS Fuzzy Noise@Speed,Particles,Bounce,Friction,Scale,Cylinder,Smear,Collide;;!;2;pal=64,sx=50,ix=200,c1=130,c2=30,c3=5,o3=1" },
  { id: 192, label: "PS Ballpit", metadata: "PS Ballpit@Speed,Intensity,Size,Hardness,Saturation,Cylinder,Walls,Ground;;!;2;pal=11,sx=100,ix=220,c1=70,c2=180,c3=31,o3=1" },
  { id: 193, label: "PS Box", metadata: "PS Box@!,Particles,Tilt,Hardness,Size,Random,Washing Machine,Sloshing;;!;2;pal=53,ix=50,c3=1,o1=1" },
  { id: 194, label: "PS Attractor", metadata: "PS Attractor@Mass,Particles,Size,Collide,Friction,AgeColor,Move,Swallow;;!;2;pal=9,sx=100,ix=82,c1=2,c2=0" },
  { id: 195, label: "PS Impact", metadata: "PS Impact@Launches,!,Force,Hardness,Blur,Cylinder,Walls,Collide;;!;2;pal=0,sx=32,ix=85,c1=70,c2=130,c3=0,o3=1" },
  { id: 196, label: "PS Waterfall", metadata: "PS Waterfall@Speed,Intensity,Variation,Collide,Position,Cylinder,Walls,Ground;;!;2;pal=9,sx=15,ix=200,c1=32,c2=160,o3=1" },
  { id: 197, label: "PS Spray", metadata: "PS Spray@Speed,!,Left/Right,Up/Down,Angle,Gravity,Cylinder/Square,Collide;;!;2v;pal=0,sx=150,ix=150,c1=220,c2=30,c3=21" },
  { id: 198, label: "PS GEQ 2D", metadata: "PS GEQ 2D@Speed,Intensity,Diverge,Bounce,Gravity,Cylinder,Walls,Floor;;!;2f;pal=0,sx=155,ix=200,c1=0" },
  { id: 199, label: "PS GEQ Nova", metadata: "PS GEQ Nova@Speed,Intensity,Rotation Speed,Color Change,Nozzle,,Direction;;!;2f;pal=13,ix=180,c1=0,c2=0,c3=8" },
  { id: 200, label: "PS Ghost Rider", metadata: "PS Ghost Rider@Speed,Spiral,Blur,Color Cycle,Spread,AgeColor,Walls;;!;2;pal=1,sx=70,ix=0,c1=220,c2=30,c3=21,o1=1" },
  { id: 201, label: "PS Blobs", metadata: "PS Blobs@Speed,Blobs,Size,Life,Blur,Wobble,Collide,Pulsate;;!;2v;sx=30,ix=64,c1=200,c2=130,c3=0,o3=1" },
  { id: 202, label: "PS DripDrop", metadata: "PS DripDrop@Speed,!,Splash,Blur,Gravity,Rain,PushSplash,Smooth;,!;!;1;pal=0,sx=150,ix=25,c1=220,c2=30,c3=21" },
  { id: 203, label: "PS Pinball", metadata: "PS Pinball@Speed,!,Size,Blur,Gravity,Collide,Rolling,Position Color;,!;!;1;pal=0,ix=220,c2=0,c3=8,o1=1" },
  { id: 204, label: "PS Dancing Shadows", metadata: "PS Dancing Shadows@Speed,!,Blur,Color Cycle,,Smear,Position Color,Smooth;,!;!;1;sx=100,ix=180,c1=0,c2=0" },
  { id: 205, label: "PS Fireworks 1D", metadata: "PS Fireworks 1D@Gravity,Explosion,Firing side,Blur,Color,Colorful,Trail,Smooth;,!;!;1;c2=30,o1=1" },
  { id: 206, label: "PS Sparkler", metadata: "PS Sparkler@Move,!,Saturation,Blur,Sparklers,Slide,Bounce,Large;,!;!;1;pal=0,sx=255,c1=0,c2=0,c3=6" },
  { id: 207, label: "PS Hourglass", metadata: "PS Hourglass@Interval,!,Color,Blur,Gravity,Colorflip,Start,Fast Reset;,!;!;1;pal=34,sx=5,ix=200,c1=140,c2=80,c3=4,o1=1,o2=1,o3=1" },
  { id: 208, label: "PS Spray 1D", metadata: "PS Spray 1D@Speed(+/-),!,Position,Blur,Gravity(+/-),AgeColor,Bounce,Position Color;,!;!;1;sx=200,ix=220,c1=0,c2=0" },
  { id: 209, label: "PS 1D Balance", metadata: "PS 1D Balance@!,!,Hardness,Blur,Tilt,Position Color,Wrap,Random;,!;!;1;pal=18,c2=0,c3=4,o1=1" },
  { id: 210, label: "PS Chase", metadata: "PS Chase@!,Density,Size,Hue,Blur,Playful,,Position Color;,!;!;1;pal=11,sx=50,c2=5,c3=0" },
  { id: 211, label: "PS Starburst", metadata: "PS Starburst@Chance,Fragments,Size,Blur,Cooling,Gravity,Colorful,Push;,!;!;1;pal=52,sx=150,ix=150,c1=120,c2=0,c3=21" },
  { id: 212, label: "PS GEQ 1D", metadata: "PS GEQ 1D@Speed,!,Size,Blur,,,,;,!;!;1f;pal=0,sx=50,ix=200,c1=0,c2=0,c3=0,o1=1,o2=1" },
  { id: 213, label: "PS Fire 1D", metadata: "PS Fire 1D@!,!,Cooling,Blur;,!;!;1;pal=35,sx=100,ix=50,c1=80,c2=100,c3=28,o1=1,o2=1" },
  { id: 214, label: "PS Sonic Stream", metadata: "PS Sonic Stream@!,!,Color,Blur,Bin,Mod,Filter,Push;,!;!;1f;c3=0,o2=1" },
  { id: 215, label: "PS Sonic Boom", metadata: "PS Sonic Boom@!,!,Color,Position,Bin,Mod,Filter,Blur;,!;!;1f;c2=63,c3=0,o2=1" },
  { id: 216, label: "PS Springy", metadata: "PS Springy@Stiffness,Damping,Density,Hue,Mode,Smear,XL,AR;,!;!;1f;pal=54,c2=0,c3=23" },
  { id: 217, label: "PS Galaxy", metadata: "PS Galaxy@!,!,Size,,Color,,Starfield,Trace;;!;2;pal=59,sx=80,c1=1,c3=4" }
];
